### ISSUE TITLE
Tags missing from manual

### ISSUE THREAD

**Issue by ghost** [ajb129/KeyakiTreebank#1]
Thanks for the great work!

The following tags occur in the treebank, but are not described in the manual:

BIND
ID
NP-1
NP-RFL
NP;*
PP-1
PP-ADV
PP-LOC
PP-MSR
PP-PRD
PP-TMP
PP-TPC
PP;*
PRN;*
ZERO
multi-sentence
ADJP
ADVP-1
CP-QUE-OB1
CP-QUE-PRD
CP-QUE-SBJ
CP-THT-ADV
IP-1
IP-ADV-PRD
NP-OB1-SBJ
PP-2
PP-TPC;SBJ
PP-VOC
PRN-1
PRO;[SHANGHAI_DISTRICT_1292}
VB;{}
CP-QUE-ADV
CP-THT-SBJ
NEG-scope
NP:{SHANGHAI_AUTO}
PP-3
CRD
PP:{SHANGHAI}
CP-1
FIXME
NML-1
NP-SBJ-PRD
PP-DIR
PP-RFL
PP-TPC-1

**Comment by ajb129** [comment]
Thanks for the issue.
Tags that are indexed, e.g., ADVP-1, NP-1 are covered by the manual in section 6.2.
Tags with ;*, e.g., PP;*, NP;* are covered in section 27.1.1.
The multi-sentence tag is covered in section 28.3 (but should be listed in section 2.4).
ID comes from the CorpusSearch formating of the annotation, see section A of the README.
CP-THT-SBJ will be documented in a future manual release.
Other tags listed are annotation mistakes, and should be corrected when there is a new release.

**Comment by ghost** [comment]
Thanks for the response and pointing me to the relevant sections in the manual!

Looking forward to a future release.
