### ISSUE TITLE
Issue parsing tree format

### ISSUE THREAD

**Issue by nikitakit** [ajb129/KeyakiTreebank#3]
I found a few instances in the treebank that don't work with some treebank processing scripts I have. Could you let me know if there's something I'm missing here?

1. How should I interpret the `*T*` here? This particular instance doesn't a POS tag around it.
https://github.com/ajb129/KeyakiTreebank/blob/48cb62860c063cc0e46d910c5ac82d64eea1d269/treebank/aozora_Natsume-1908.psd#L13714-L13715

2. The `g` on line 1011 causes an error in my data reader scripts.
https://github.com/ajb129/KeyakiTreebank/blob/48cb62860c063cc0e46d910c5ac82d64eea1d269/treebank/spoken_JF13.psd#L1009-L1012

**Comment by ajb129** [comment]
Many thanks for reporting these. They are mistakes and are corrected now.
